name: Sync Fork

on:
  push:
    branches:
      - 'fork-sync'
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.6.3
        with:
          token: ${{ github.token }}
          base: staging
          head: master
          pr_title: Upstream sync